### ISSUE TITLE
Linter & Indent

### ISSUE THREAD

**Issue by PierreBrisorgueil** [weareopensource/MEANie#12]

**Comment by techla** [comment]
Angular starter code base is now tslint compliant. Some additional rule should be added plus a code formater that takes care of the tsconfig file.

**Comment by techla** [comment]
Adding https://github.com/blakeembrey/tslint-config-standard and adapting the code base to be compliant

**Comment by PierreBrisorgueil** [comment]
done https://github.com/weareopensource/Node/pull/35
